### ISSUE TITLE
Could NOT configuration file 

### ISSUE THREAD

**Issue by frank8g2g3** [wacai/spring-boot-starter-logback-access#4]
11:22:36,983 |-INFO in ch.qos.logback.access.tomcat.LogbackValve[null] - Could NOT configuration file [/private/var/folders/c4/bzb_0dy54r7_55xzd__zry_m0000gn/T/tomcat.3539471340404148365.8080//Users/francis/repo/nbugs/demo/jpa-demo/target/classes/logback-access.xml] using property "catalina.base"
11:22:36,983 |-INFO in ch.qos.logback.access.tomcat.LogbackValve[null] - Could NOT configuration file [/private/var/folders/c4/bzb_0dy54r7_55xzd__zry_m0000gn/T/tomcat.3539471340404148365.8080//Users/francis/repo/nbugs/demo/jpa-demo/target/classes/logback-access.xml] using property "catalina.home"
11:22:36,984 |-INFO in ch.qos.logback.access.tomcat.LogbackValve[null] - Could NOT find [/Users/francis/repo/nbugs/demo/jpa-demo/target/classes/logback-access.xml] as a resource.
11:22:36,984 |-WARN in ch.qos.logback.access.tomcat.LogbackValve[null] - Failed to find valid logback-access configuration file.

**Comment by joshwand** [comment]
Finally solved this for myself in my own autoconfig:

at https://github.com/wacai/spring-boot-starter-logback-access/blob/master/src/main/java/com/wacai/springboot/logback/access/LogbackAccessConfiguration.java#L37

add `logbackValve.setQuiet(true);`

**Comment by zhongl** [comment]
Thanks @joshwand
